# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy production

on:
  push:
    branches: ["master"]
jobs:
  build-run-tests:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      NODE_ENV: test
      username: ${{ secrets.db_username }}
      password: ${{ secrets.db_password }}
      database: nftng_test
      host: ${{ secrets.db_host_test }}
      dialect: mysql
      port: ${{ secrets.db_port_test }}
      accessKey: ${{ secrets.spaces_access_key_test }}
      secretKey: ${{ secrets.spaces_secret_key_test }}
      endPoint: ${{ secrets.spaces_end_point_test }}
      spacesName: ${{ secrets.spaces_name_test }}
      paystackSecretKey: ${{ secrets.paystack_secret }}
      nft_contract_address: "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D"
      infura_key: ${{ secrets.infura_secret }}
      discount_amount: "10"

      admin_email: "username"
      admin_password: "password"
      jwt_key: "thisIsTheKey"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn test
  start-app:
    needs: build-run-tests
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: sudo pm2 stop ecosystem.config.js
      - run: yarn
      - name: remove env file
        run: rm -rf .env*
      - name: creating env file
        run: |
          touch .env
          echo db_username=${{ secrets.db_username }} >> .env
          echo db_password=${{ secrets.db_password }} >> .env
          echo database="nftng_prod" >> .env
          echo host=${{ secrets.db_host }} >> .env
          echo dialect=mysql >> .env
          echo port=${{ secrets.db_port }} >> .env
          echo accessKey=${{ secrets.spaces_access_key }} >> .env
          echo secretKey=${{ secrets.spaces_secret_key }} >> .env
          echo endPoint=${{ secrets.spaces_end_point }} >> .env
          echo spacesName=${{ secrets.spaces_name }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo paystackSecretKey=${{ secrets.paystack_secret }} >> .env
          echo nft_contract_address=0x256ECd277670507Fd835C965079d27d3811Ba4F2 >> .env
          echo infura_key=${{ secrets.infura_secret }} >> .env
          echo discount_amount=5 >> .env
          echo gold_discount_amount=10 >> .env
          echo default_city_name=yaba >> .env
          echo default_country_code=NG >> .env
          echo default_weight=1 >> .env
          echo admin_email=${{ secrets.admin_email }} >> .env
          echo admin_password=${{ secrets.admin_password }} >> .env
          echo jwt_key=${{ secrets.jwt_key }} >> .env
      - run: sudo pm2 start ecosystem.config-prod.js
